<?
$noteSelFile = array("en" => "Please select a copy of data","cn" => "请选择一份数据");
$tconsole = array("en" => "Console","cn" => "管理控制台");
$tcontents = array("en" => "Content","cn" => "内容管理");
$tcontentlist = array("en" => "Content list","cn" => "内容列表");
$tcontentedit = array("en" => "Content edit","cn" => "内容编辑");
$treplies = array("en" => "Replies","cn" => "回复管理");
$tblock = array("en" => "Category","cn" => "版块管理");
$tslider = array("en" => "Slider","cn" => "头图管理");
$tpublish = array("en" => "Publish","cn" => "发布管理");
$tsetting = array("en" => "Setting","cn" => "系统设置");
$tdoset = array("en" => "Setting","cn" => "参数设置");
$ttheme = array("en" => "Theme","cn" => "主题管理");
$tlanguage = array("en" => "Language","cn" => "语言设置");
$tother = array("en" => "Other","cn" => "其他");
$tdatamng = array("en" => "Backup","cn" => "数据管理");
$tbackup = array("en" => "Backup","cn" => "数据备份");
$tclear = array("en" => "Clear all","cn" => "一键清理");
$trestore = array("en" => "Restore","cn" => "数据恢复");
$tlog = array("en" => "System Log","cn" => "系统日志");
$tpassword = array("en" => "Password","cn" => "修改密码");
$tsuccess = array("en" => "Success","cn" => "操作成功");
$tfailed = array("en" => "Failed","cn" => "操作失败");
$tedit = array("en" => "Edit","cn" => "编辑内容");
$tcategory = array("en" => "Category","cn" => "分类");
$tselect = array("en" => "Select","cn" => "请选择");
$ttitle = array("en" => "Title","cn" => "标题");
$tkeyword = array("en" => "Keyword ","cn" => "标签");
$tstatus = array("en" => "Status","cn" => "状态");
$tpublished = array("en" => "Published","cn" => "已发布");
$ttopublished = array("en" => "Normal","cn" => "正常");
$tdraft = array("en" => "Draft","cn" => "草稿");
$ttext = array("en" => "Content","cn" => "文本内容");
$tsave = array("en" => "Save","cn" => "保存");
$tclose = array("en" => "Close","cn" => "关闭");
$tquery = array("en" => "Query","cn" => "查询");
$tadd = array("en" => "Add","cn" => "新增");
$tuser = array("en" => "Author","cn" => "用户名");
$taddarticle = array("en" => "Write an article","cn" => "新写一篇");
$tleft = array("en" => "Left","cn" => "左侧");
$tcenter = array("en" => "Center","cn" => "主页面");
$tright = array("en" => "Right","cn" => "右侧");
$toperation = array("en" => "Operation","cn" => "操作");
$tdelete = array("en" => "Delete","cn" => "删除");
$tbatchdelete = array("en" => "Batch Delete","cn" => "批量删除");
$tmodify = array("en" => "Edit","cn" => "修改");
$tview = array("en" => "View","cn" => "查看");
$ttop = array("en" => "Top","cn" => "置顶");
$tuntop = array("en" => "Un-Top","cn" => "取消置顶");
$tinputtm = array("en" => "Input Time","cn" => "输入时间");
$tedittm = array("en" => "Last Edit Time","cn" => "最后编辑时间");
$publishtm = array("en" => "Publish Time","cn" => "发布时间");
$visits = array("en" => "Visits","cn" => "阅读量");
$topnum = array("en" => "Top","cn" => "被顶次数");
$replyctx = array("en" => "Reply","cn" => "回复内容");
$oritile = array("en" => "Article Title","cn" => "原文标题");
$oriid = array("en" => "ArticleID","cn" => "原文ID");
$replyid = array("en" => "ReplyID","cn" => "回复ID");
$tfirst = array("en" => "First","cn" => "首页");
$tlast = array("en" => "Last","cn" => "末页");
$tpre = array("en" => "Pre","cn" => "上一页");
$tnext = array("en" => "Next","cn" => "下一页");
$tskip = array("en" => "Skip","cn" => "跳转");
$tperpage = array("en" => "Perpage","cn" => "每页显示");
$ttotal = array("en" => "Total ","cn" => "总记录数");
$timage = array("en" => "Image","cn" => "图标");
$tbrowse = array("en" => "Browse","cn" => "浏览");
$tupload = array("en" => "Upload","cn" => "上传");
$tuploadsuc = array("en" => "Upload success","cn" => "上传成功!");
$tuploadfail = array("en" => "Upload failed","cn" => "上传失败!");
$torder = array("en" => "Order","cn" => "序号");
$tname = array("en" => "Name","cn" => "名称");
$tposition = array("en" => "Position","cn" => "位置");
$tlink = array("en" => "Link","cn" => "超级链接");
$tincrepublish = array("en" => "Publish New","cn" => "增量发布");
$ttopublish = array("en" => "Publish All","cn" => "整站发布");
$tpubpreview = array("en" => "Publish preview","cn" => "发布预览");
$tsitename = array("en" => "Sitename ","cn" => "站点名");
$tdescription = array("en" => "Description ","cn" => "站点描述");
$twebroot = array("en" => "Webroot","cn" => "站点根目录");
$taccstat = array("en" => "Access statistics code","cn" => "访问统计代码");
$thomemaxnum = array("en" => "Home records","cn" => "首页最大显示数量");
$tnewmaxnum = array("en" => "New records","cn" => "最新内容显示数量");
$ttopmaxnum = array("en" => "Top visits records","cn" => "最高点击显示数量");
$tcommentswitch = array("en" => "Comment function","cn" => "评论功能");
$tcommentdspnum = array("en" => "Comment display number","cn" => "显示评论条数");
$tactive = array("en" => "Active","cn" => "启用");
$tok = array("en" => "OK","cn" => "确定");
$tpwdtips = array("en" => "Incorrect","cn" => "原密码输入错误!");
$tdiffpwdtips = array("en" => "Do not match","cn" => "密码输入不匹配!");
$tpwdori = array("en" => "Passwrod","cn" => "请输入原密码");
$tpwdnew = array("en" => "New password","cn" => "请输入新密码");
$tconfirmpwd = array("en" => "Confirm","cn" => "再输入一遍");
$tconfirm = array("en" => "Confirm","cn" => "确认");
$thomepage = array("en" => "Homepage","cn" => "网站首页");
$tlogout = array("en" => "Logout","cn" => "退出登录");
$tlogerr = array("en" => "Username or password is wrong","cn" => "用户名或密码错误");
$trestoretips = array("en" => "Restore failed, please check the syslog","cn" => "恢复失败,具体细节请查看系统日志");
$ttitletips = array("en" => "Please input title","cn" => "请输入标题");
$ton = array("en" => "On","cn" => "开");
$toff = array("en" => "Off","cn" => "关");
$tblocktips = array("en" => "Please input block name","cn" => "请输入分类名");
$tcattips = array("en" => "Please create a category first","cn" => "请先创建一个分类");
$tnoseltips = array("en" => "Please input title","cn" => "未选择任何项");
$tbasedelerror = array("en" => "Please do not delete the base theme!","cn" => "请不要删除基础主题!");
$tuploadtips = array("en" => "Click picture to upload another one","cn" => "点击当前图片以上传另一张");
$theadimg = array("en" => "Home picture","cn" => "首页头图");
$statistics = array("en" => "Dashboard","cn" => "站点信息");
$content_count = array("en" => "Content count","cn" => "文章总数");
$visits_count = array("en" => "Visits count","cn" => "总阅读量");
$block_count = array("en" => "Block count","cn" => "分类总数");
$replies_count = array("en" => "Replies count","cn" => "总回复数");
$os_ver = array("en" => "OS version","cn" => "操作系统");
$server_ip = array("en" => "Server IP","cn" => "服务器IP");
$webserver = array("en" => "Web server","cn" => "服务端软件");
$domain_name = array("en" => "Domain name","cn" => "网站域名");
 $software_version = array("en" => "Software version","cn" => "软件版本");
$offi_website = array("en" => "Official website","cn" => "官方网站");      
$conv_fun = array("en" => "Convenient Function","cn" => "便捷功能"); 
$pers_setting = array("en" => "Personalized setting","cn" => "个性化设置"); 
$tnotice = array("en" => "Notice","cn" => "网站公告"); 
/** site content **/
include "site.php"; 
$block_pos = array("-1" => "$tleft[$lan]","0" => "$tcenter[$lan]","1" => "$tright[$lan]");
$content_sts = array("-1" => "$tdraft[$lan]","0" => "$ttopublished[$lan]","1" => "$tpublished[$lan]");
